// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: redis_service/protobuff/redis.proto

package protobuff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationsNames string `protobuf:"bytes,1,opt,name=StationsNames,proto3" json:"StationsNames,omitempty"`
}

func (x *Stations) Reset() {
	*x = Stations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_service_protobuff_redis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stations) ProtoMessage() {}

func (x *Stations) ProtoReflect() protoreflect.Message {
	mi := &file_redis_service_protobuff_redis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stations.ProtoReflect.Descriptor instead.
func (*Stations) Descriptor() ([]byte, []int) {
	return file_redis_service_protobuff_redis_proto_rawDescGZIP(), []int{0}
}

func (x *Stations) GetStationsNames() string {
	if x != nil {
		return x.StationsNames
	}
	return ""
}

type SearchWorkloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationName string `protobuf:"bytes,1,opt,name=StationName,proto3" json:"StationName,omitempty"`
	Workload    string `protobuf:"bytes,2,opt,name=Workload,proto3" json:"Workload,omitempty"`
}

func (x *SearchWorkloadResponse) Reset() {
	*x = SearchWorkloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_service_protobuff_redis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchWorkloadResponse) ProtoMessage() {}

func (x *SearchWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_service_protobuff_redis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchWorkloadResponse.ProtoReflect.Descriptor instead.
func (*SearchWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_redis_service_protobuff_redis_proto_rawDescGZIP(), []int{1}
}

func (x *SearchWorkloadResponse) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

func (x *SearchWorkloadResponse) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

type StoreWorkloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Station  string `protobuf:"bytes,1,opt,name=Station,proto3" json:"Station,omitempty"`
	Workload string `protobuf:"bytes,2,opt,name=Workload,proto3" json:"Workload,omitempty"`
}

func (x *StoreWorkloadRequest) Reset() {
	*x = StoreWorkloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_service_protobuff_redis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreWorkloadRequest) ProtoMessage() {}

func (x *StoreWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_service_protobuff_redis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreWorkloadRequest.ProtoReflect.Descriptor instead.
func (*StoreWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_redis_service_protobuff_redis_proto_rawDescGZIP(), []int{2}
}

func (x *StoreWorkloadRequest) GetStation() string {
	if x != nil {
		return x.Station
	}
	return ""
}

func (x *StoreWorkloadRequest) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

type ErrorMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *ErrorMsg) Reset() {
	*x = ErrorMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_service_protobuff_redis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMsg) ProtoMessage() {}

func (x *ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_redis_service_protobuff_redis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMsg.ProtoReflect.Descriptor instead.
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return file_redis_service_protobuff_redis_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorMsg) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_redis_service_protobuff_redis_proto protoreflect.FileDescriptor

var file_redis_service_protobuff_redis_proto_rawDesc = []byte{
	0x0a, 0x23, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x56, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x4c, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x21, 0x0a,
	0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x32, 0x7a, 0x0a, 0x0c, 0x52, 0x65, 0x64, 0x69, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x32, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x15, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x6d, 0x73, 0x67, 0x12, 0x36, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x09, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x1a, 0x17, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x1a, 0x5a, 0x18,
	0x2f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_redis_service_protobuff_redis_proto_rawDescOnce sync.Once
	file_redis_service_protobuff_redis_proto_rawDescData = file_redis_service_protobuff_redis_proto_rawDesc
)

func file_redis_service_protobuff_redis_proto_rawDescGZIP() []byte {
	file_redis_service_protobuff_redis_proto_rawDescOnce.Do(func() {
		file_redis_service_protobuff_redis_proto_rawDescData = protoimpl.X.CompressGZIP(file_redis_service_protobuff_redis_proto_rawDescData)
	})
	return file_redis_service_protobuff_redis_proto_rawDescData
}

var file_redis_service_protobuff_redis_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_redis_service_protobuff_redis_proto_goTypes = []interface{}{
	(*Stations)(nil),               // 0: Stations
	(*SearchWorkloadResponse)(nil), // 1: SearchWorkloadResponse
	(*StoreWorkloadRequest)(nil),   // 2: StoreWorkloadRequest
	(*ErrorMsg)(nil),               // 3: Error_msg
}
var file_redis_service_protobuff_redis_proto_depIdxs = []int32{
	2, // 0: RedisService.StoreWorkload:input_type -> StoreWorkloadRequest
	0, // 1: RedisService.SearchWorkload:input_type -> Stations
	3, // 2: RedisService.StoreWorkload:output_type -> Error_msg
	1, // 3: RedisService.SearchWorkload:output_type -> SearchWorkloadResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_redis_service_protobuff_redis_proto_init() }
func file_redis_service_protobuff_redis_proto_init() {
	if File_redis_service_protobuff_redis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_redis_service_protobuff_redis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_service_protobuff_redis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchWorkloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_service_protobuff_redis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreWorkloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_service_protobuff_redis_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redis_service_protobuff_redis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redis_service_protobuff_redis_proto_goTypes,
		DependencyIndexes: file_redis_service_protobuff_redis_proto_depIdxs,
		MessageInfos:      file_redis_service_protobuff_redis_proto_msgTypes,
	}.Build()
	File_redis_service_protobuff_redis_proto = out.File
	file_redis_service_protobuff_redis_proto_rawDesc = nil
	file_redis_service_protobuff_redis_proto_goTypes = nil
	file_redis_service_protobuff_redis_proto_depIdxs = nil
}
