// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: protobuf/stations.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStationWorkloadFromDBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationName string `protobuf:"bytes,1,opt,name=stationName,proto3" json:"stationName,omitempty"`
}

func (x *GetStationWorkloadFromDBRequest) Reset() {
	*x = GetStationWorkloadFromDBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_stations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStationWorkloadFromDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationWorkloadFromDBRequest) ProtoMessage() {}

func (x *GetStationWorkloadFromDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_stations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationWorkloadFromDBRequest.ProtoReflect.Descriptor instead.
func (*GetStationWorkloadFromDBRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_stations_proto_rawDescGZIP(), []int{0}
}

func (x *GetStationWorkloadFromDBRequest) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

type GetStationWorkloadFromDBResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespstationName string              `protobuf:"bytes,1,opt,name=RespstationName,proto3" json:"RespstationName,omitempty"`
	RespWorkLoad    map[string]*DayWork `protobuf:"bytes,2,rep,name=RespWorkLoad,proto3" json:"RespWorkLoad,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Error           string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *GetStationWorkloadFromDBResponse) Reset() {
	*x = GetStationWorkloadFromDBResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_stations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStationWorkloadFromDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationWorkloadFromDBResponse) ProtoMessage() {}

func (x *GetStationWorkloadFromDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_stations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationWorkloadFromDBResponse.ProtoReflect.Descriptor instead.
func (*GetStationWorkloadFromDBResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_stations_proto_rawDescGZIP(), []int{1}
}

func (x *GetStationWorkloadFromDBResponse) GetRespstationName() string {
	if x != nil {
		return x.RespstationName
	}
	return ""
}

func (x *GetStationWorkloadFromDBResponse) GetRespWorkLoad() map[string]*DayWork {
	if x != nil {
		return x.RespWorkLoad
	}
	return nil
}

func (x *GetStationWorkloadFromDBResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetStationWorkloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationName string `protobuf:"bytes,1,opt,name=stationName,proto3" json:"stationName,omitempty"`
	IsUpdateDB  bool   `protobuf:"varint,2,opt,name=isUpdateDB,proto3" json:"isUpdateDB,omitempty"`
}

func (x *GetStationWorkloadRequest) Reset() {
	*x = GetStationWorkloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_stations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStationWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationWorkloadRequest) ProtoMessage() {}

func (x *GetStationWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_stations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationWorkloadRequest.ProtoReflect.Descriptor instead.
func (*GetStationWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_stations_proto_rawDescGZIP(), []int{2}
}

func (x *GetStationWorkloadRequest) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

func (x *GetStationWorkloadRequest) GetIsUpdateDB() bool {
	if x != nil {
		return x.IsUpdateDB
	}
	return false
}

type DayWork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DayWorkload map[int32]string `protobuf:"bytes,1,rep,name=DayWorkload,proto3" json:"DayWorkload,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DayWork) Reset() {
	*x = DayWork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_stations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayWork) ProtoMessage() {}

func (x *DayWork) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_stations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayWork.ProtoReflect.Descriptor instead.
func (*DayWork) Descriptor() ([]byte, []int) {
	return file_protobuf_stations_proto_rawDescGZIP(), []int{3}
}

func (x *DayWork) GetDayWorkload() map[int32]string {
	if x != nil {
		return x.DayWorkload
	}
	return nil
}

type GetStationWorkloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkLoad map[string]*DayWork `protobuf:"bytes,1,rep,name=WorkLoad,proto3" json:"WorkLoad,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Error    string              `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *GetStationWorkloadResponse) Reset() {
	*x = GetStationWorkloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_stations_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStationWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationWorkloadResponse) ProtoMessage() {}

func (x *GetStationWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_stations_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationWorkloadResponse.ProtoReflect.Descriptor instead.
func (*GetStationWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_stations_proto_rawDescGZIP(), []int{4}
}

func (x *GetStationWorkloadResponse) GetWorkLoad() map[string]*DayWork {
	if x != nil {
		return x.WorkLoad
	}
	return nil
}

func (x *GetStationWorkloadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protobuf_stations_proto protoreflect.FileDescriptor

var file_protobuf_stations_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x1f, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x46,
	0x72, 0x6f, 0x6d, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x86,
	0x02, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x52, 0x65,
	0x73, 0x70, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x57, 0x0a,
	0x0c, 0x52, 0x65, 0x73, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x42, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x4c,
	0x6f, 0x61, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x57, 0x6f,
	0x72, 0x6b, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x49, 0x0a, 0x11,
	0x52, 0x65, 0x73, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x61, 0x64, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x44, 0x61, 0x79, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5d, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x42, 0x22, 0x86, 0x01, 0x0a, 0x07, 0x44, 0x61, 0x79, 0x57, 0x6f,
	0x72, 0x6b, 0x12, 0x3b, 0x0a, 0x0b, 0x44, 0x61, 0x79, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x44, 0x61, 0x79, 0x57, 0x6f, 0x72,
	0x6b, 0x2e, 0x44, 0x61, 0x79, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0b, 0x44, 0x61, 0x79, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x1a,
	0x3e, 0x0a, 0x10, 0x44, 0x61, 0x79, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xc0, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45,
	0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x4c, 0x6f, 0x61, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x57, 0x6f, 0x72,
	0x6b, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x45, 0x0a, 0x0d, 0x57,
	0x6f, 0x72, 0x6b, 0x4c, 0x6f, 0x61, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x44, 0x61, 0x79, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x32, 0xbb, 0x01, 0x0a, 0x09, 0x4d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57,
	0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5f, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x42, 0x12, 0x20, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x46, 0x72, 0x6f, 0x6d, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_stations_proto_rawDescOnce sync.Once
	file_protobuf_stations_proto_rawDescData = file_protobuf_stations_proto_rawDesc
)

func file_protobuf_stations_proto_rawDescGZIP() []byte {
	file_protobuf_stations_proto_rawDescOnce.Do(func() {
		file_protobuf_stations_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_stations_proto_rawDescData)
	})
	return file_protobuf_stations_proto_rawDescData
}

var file_protobuf_stations_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protobuf_stations_proto_goTypes = []interface{}{
	(*GetStationWorkloadFromDBRequest)(nil),  // 0: GetStationWorkloadFromDBRequest
	(*GetStationWorkloadFromDBResponse)(nil), // 1: GetStationWorkloadFromDBResponse
	(*GetStationWorkloadRequest)(nil),        // 2: GetStationWorkloadRequest
	(*DayWork)(nil),                          // 3: DayWork
	(*GetStationWorkloadResponse)(nil),       // 4: GetStationWorkloadResponse
	nil,                                      // 5: GetStationWorkloadFromDBResponse.RespWorkLoadEntry
	nil,                                      // 6: DayWork.DayWorkloadEntry
	nil,                                      // 7: GetStationWorkloadResponse.WorkLoadEntry
}
var file_protobuf_stations_proto_depIdxs = []int32{
	5, // 0: GetStationWorkloadFromDBResponse.RespWorkLoad:type_name -> GetStationWorkloadFromDBResponse.RespWorkLoadEntry
	6, // 1: DayWork.DayWorkload:type_name -> DayWork.DayWorkloadEntry
	7, // 2: GetStationWorkloadResponse.WorkLoad:type_name -> GetStationWorkloadResponse.WorkLoadEntry
	3, // 3: GetStationWorkloadFromDBResponse.RespWorkLoadEntry.value:type_name -> DayWork
	3, // 4: GetStationWorkloadResponse.WorkLoadEntry.value:type_name -> DayWork
	2, // 5: MyService.GetStationWorkload:input_type -> GetStationWorkloadRequest
	0, // 6: MyService.GetStationWorkloadFromDB:input_type -> GetStationWorkloadFromDBRequest
	4, // 7: MyService.GetStationWorkload:output_type -> GetStationWorkloadResponse
	1, // 8: MyService.GetStationWorkloadFromDB:output_type -> GetStationWorkloadFromDBResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protobuf_stations_proto_init() }
func file_protobuf_stations_proto_init() {
	if File_protobuf_stations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_stations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStationWorkloadFromDBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_stations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStationWorkloadFromDBResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_stations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStationWorkloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_stations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayWork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_stations_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStationWorkloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_stations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_stations_proto_goTypes,
		DependencyIndexes: file_protobuf_stations_proto_depIdxs,
		MessageInfos:      file_protobuf_stations_proto_msgTypes,
	}.Build()
	File_protobuf_stations_proto = out.File
	file_protobuf_stations_proto_rawDesc = nil
	file_protobuf_stations_proto_goTypes = nil
	file_protobuf_stations_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MyServiceClient is the client API for MyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyServiceClient interface {
	GetStationWorkload(ctx context.Context, in *GetStationWorkloadRequest, opts ...grpc.CallOption) (*GetStationWorkloadResponse, error)
	GetStationWorkloadFromDB(ctx context.Context, in *GetStationWorkloadFromDBRequest, opts ...grpc.CallOption) (*GetStationWorkloadFromDBResponse, error)
}

type myServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyServiceClient(cc grpc.ClientConnInterface) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) GetStationWorkload(ctx context.Context, in *GetStationWorkloadRequest, opts ...grpc.CallOption) (*GetStationWorkloadResponse, error) {
	out := new(GetStationWorkloadResponse)
	err := c.cc.Invoke(ctx, "/MyService/GetStationWorkload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) GetStationWorkloadFromDB(ctx context.Context, in *GetStationWorkloadFromDBRequest, opts ...grpc.CallOption) (*GetStationWorkloadFromDBResponse, error) {
	out := new(GetStationWorkloadFromDBResponse)
	err := c.cc.Invoke(ctx, "/MyService/GetStationWorkloadFromDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyServiceServer is the server API for MyService service.
type MyServiceServer interface {
	GetStationWorkload(context.Context, *GetStationWorkloadRequest) (*GetStationWorkloadResponse, error)
	GetStationWorkloadFromDB(context.Context, *GetStationWorkloadFromDBRequest) (*GetStationWorkloadFromDBResponse, error)
}

// UnimplementedMyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMyServiceServer struct {
}

func (*UnimplementedMyServiceServer) GetStationWorkload(context.Context, *GetStationWorkloadRequest) (*GetStationWorkloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStationWorkload not implemented")
}
func (*UnimplementedMyServiceServer) GetStationWorkloadFromDB(context.Context, *GetStationWorkloadFromDBRequest) (*GetStationWorkloadFromDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStationWorkloadFromDB not implemented")
}

func RegisterMyServiceServer(s *grpc.Server, srv MyServiceServer) {
	s.RegisterService(&_MyService_serviceDesc, srv)
}

func _MyService_GetStationWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).GetStationWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MyService/GetStationWorkload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).GetStationWorkload(ctx, req.(*GetStationWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_GetStationWorkloadFromDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationWorkloadFromDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).GetStationWorkloadFromDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MyService/GetStationWorkloadFromDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).GetStationWorkloadFromDB(ctx, req.(*GetStationWorkloadFromDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStationWorkload",
			Handler:    _MyService_GetStationWorkload_Handler,
		},
		{
			MethodName: "GetStationWorkloadFromDB",
			Handler:    _MyService_GetStationWorkloadFromDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/stations.proto",
}
