// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyServiceClient is the client API for MyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyServiceClient interface {
	GetStationWorkload(ctx context.Context, in *GetStationWorkloadRequest, opts ...grpc.CallOption) (MyService_GetStationWorkloadClient, error)
	// rpc GetStationWorkload(GetStationWorkloadRequest) returns (GetStationWorkloadResponse){
	//     option (google.api.http) = {
	//       get: "/{stationName}/{isUpdateDB}"
	//     };
	//   }
	GetStationWorkloadFromDB(ctx context.Context, in *GetStationWorkloadFromDBRequest, opts ...grpc.CallOption) (*GetStationWorkloadFromDBResponse, error)
}

type myServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyServiceClient(cc grpc.ClientConnInterface) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) GetStationWorkload(ctx context.Context, in *GetStationWorkloadRequest, opts ...grpc.CallOption) (MyService_GetStationWorkloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &MyService_ServiceDesc.Streams[0], "/MyService/GetStationWorkload", opts...)
	if err != nil {
		return nil, err
	}
	x := &myServiceGetStationWorkloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MyService_GetStationWorkloadClient interface {
	Recv() (*StationData, error)
	grpc.ClientStream
}

type myServiceGetStationWorkloadClient struct {
	grpc.ClientStream
}

func (x *myServiceGetStationWorkloadClient) Recv() (*StationData, error) {
	m := new(StationData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *myServiceClient) GetStationWorkloadFromDB(ctx context.Context, in *GetStationWorkloadFromDBRequest, opts ...grpc.CallOption) (*GetStationWorkloadFromDBResponse, error) {
	out := new(GetStationWorkloadFromDBResponse)
	err := c.cc.Invoke(ctx, "/MyService/GetStationWorkloadFromDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyServiceServer is the server API for MyService service.
// All implementations must embed UnimplementedMyServiceServer
// for forward compatibility
type MyServiceServer interface {
	GetStationWorkload(*GetStationWorkloadRequest, MyService_GetStationWorkloadServer) error
	// rpc GetStationWorkload(GetStationWorkloadRequest) returns (GetStationWorkloadResponse){
	//     option (google.api.http) = {
	//       get: "/{stationName}/{isUpdateDB}"
	//     };
	//   }
	GetStationWorkloadFromDB(context.Context, *GetStationWorkloadFromDBRequest) (*GetStationWorkloadFromDBResponse, error)
	mustEmbedUnimplementedMyServiceServer()
}

// UnimplementedMyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMyServiceServer struct {
}

func (UnimplementedMyServiceServer) GetStationWorkload(*GetStationWorkloadRequest, MyService_GetStationWorkloadServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStationWorkload not implemented")
}
func (UnimplementedMyServiceServer) GetStationWorkloadFromDB(context.Context, *GetStationWorkloadFromDBRequest) (*GetStationWorkloadFromDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStationWorkloadFromDB not implemented")
}
func (UnimplementedMyServiceServer) mustEmbedUnimplementedMyServiceServer() {}

// UnsafeMyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyServiceServer will
// result in compilation errors.
type UnsafeMyServiceServer interface {
	mustEmbedUnimplementedMyServiceServer()
}

func RegisterMyServiceServer(s grpc.ServiceRegistrar, srv MyServiceServer) {
	s.RegisterService(&MyService_ServiceDesc, srv)
}

func _MyService_GetStationWorkload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetStationWorkloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MyServiceServer).GetStationWorkload(m, &myServiceGetStationWorkloadServer{stream})
}

type MyService_GetStationWorkloadServer interface {
	Send(*StationData) error
	grpc.ServerStream
}

type myServiceGetStationWorkloadServer struct {
	grpc.ServerStream
}

func (x *myServiceGetStationWorkloadServer) Send(m *StationData) error {
	return x.ServerStream.SendMsg(m)
}

func _MyService_GetStationWorkloadFromDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationWorkloadFromDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).GetStationWorkloadFromDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MyService/GetStationWorkloadFromDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).GetStationWorkloadFromDB(ctx, req.(*GetStationWorkloadFromDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MyService_ServiceDesc is the grpc.ServiceDesc for MyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStationWorkloadFromDB",
			Handler:    _MyService_GetStationWorkloadFromDB_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStationWorkload",
			Handler:       _MyService_GetStationWorkload_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuff/stations.proto",
}
